/* Sidebar.svelte generated by Svelte v4.2.20 */
import {
	SvelteComponent,
	append,
	append_styles,
	attr,
	destroy_each,
	detach,
	element,
	ensure_array_like,
	init,
	insert,
	listen,
	noop,
	run_all,
	safe_not_equal,
	space,
	toggle_class
} from "svelte/internal";

import "svelte/internal/disclose-version";
import { createEventDispatcher } from 'svelte';

function add_css(target) {
	append_styles(target, "svelte-a57opy", ".sidebar.svelte-a57opy.svelte-a57opy{width:260px;height:100%;display:flex;flex-direction:column;background-color:var(--bg-secondary);border-right:1px solid var(--border-color);flex-shrink:0}.sidebar-header.svelte-a57opy.svelte-a57opy{padding:var(--spacing-md);border-bottom:1px solid var(--border-color)}.logo.svelte-a57opy.svelte-a57opy{display:flex;align-items:center;gap:var(--spacing-sm);font-weight:600;font-size:16px;color:var(--accent-primary)}.sidebar-content.svelte-a57opy.svelte-a57opy{flex:1;overflow-y:auto;padding:var(--spacing-md)}.nav-section.svelte-a57opy.svelte-a57opy{margin-top:var(--spacing-lg)}.nav-section.svelte-a57opy.svelte-a57opy:first-of-type{margin-top:var(--spacing-md)}.nav-title.svelte-a57opy.svelte-a57opy{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;color:var(--text-muted);margin-bottom:var(--spacing-sm);padding:0 var(--spacing-sm)}.nav-list.svelte-a57opy.svelte-a57opy{list-style:none}.nav-item.svelte-a57opy.svelte-a57opy{width:100%;display:flex;align-items:center;gap:var(--spacing-sm);padding:var(--spacing-sm) var(--spacing-md);font-size:14px;color:var(--text-secondary);background:none;border:none;border-radius:var(--radius-md);cursor:pointer;transition:all var(--transition-fast);text-align:left}.nav-item.svelte-a57opy.svelte-a57opy:hover{background-color:var(--bg-hover);color:var(--text-primary)}.nav-item.active.svelte-a57opy.svelte-a57opy{background-color:var(--accent-light);color:var(--accent-primary)}.nav-icon.svelte-a57opy.svelte-a57opy{width:20px;text-align:center}.nav-label.svelte-a57opy.svelte-a57opy{flex:1}.sidebar-footer.svelte-a57opy.svelte-a57opy{padding:var(--spacing-md);border-top:1px solid var(--border-color)}.footer-actions.svelte-a57opy.svelte-a57opy{display:flex;gap:var(--spacing-sm);margin-bottom:var(--spacing-sm)}.footer-actions.svelte-a57opy .btn.svelte-a57opy{flex:1}");
}

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[12] = list[i];
	return child_ctx;
}

// (46:8) {#each categories as category}
function create_each_block(ctx) {
	let li;
	let button;
	let span0;
	let t1;
	let span1;
	let t3;
	let mounted;
	let dispose;

	function click_handler_1() {
		return /*click_handler_1*/ ctx[7](/*category*/ ctx[12]);
	}

	return {
		c() {
			li = element("li");
			button = element("button");
			span0 = element("span");
			span0.textContent = `${/*category*/ ctx[12].icon}`;
			t1 = space();
			span1 = element("span");
			span1.textContent = `${/*category*/ ctx[12].label}`;
			t3 = space();
			attr(span0, "class", "nav-icon svelte-a57opy");
			attr(span1, "class", "nav-label svelte-a57opy");
			attr(button, "class", "nav-item svelte-a57opy");
			toggle_class(button, "active", /*selectedCategory*/ ctx[0] === /*category*/ ctx[12].id && /*currentView*/ ctx[1] === 'notes');
		},
		m(target, anchor) {
			insert(target, li, anchor);
			append(li, button);
			append(button, span0);
			append(button, t1);
			append(button, span1);
			append(li, t3);

			if (!mounted) {
				dispose = listen(button, "click", click_handler_1);
				mounted = true;
			}
		},
		p(new_ctx, dirty) {
			ctx = new_ctx;

			if (dirty & /*selectedCategory, categories, currentView*/ 11) {
				toggle_class(button, "active", /*selectedCategory*/ ctx[0] === /*category*/ ctx[12].id && /*currentView*/ ctx[1] === 'notes');
			}
		},
		d(detaching) {
			if (detaching) {
				detach(li);
			}

			mounted = false;
			dispose();
		}
	};
}

function create_fragment(ctx) {
	let aside;
	let div1;
	let t2;
	let div2;
	let button0;
	let t4;
	let nav0;
	let h30;
	let t6;
	let ul0;
	let t7;
	let nav1;
	let h31;
	let t9;
	let ul1;
	let li;
	let button1;
	let t13;
	let div4;
	let div3;
	let button2;
	let t15;
	let button3;
	let t17;
	let button4;
	let mounted;
	let dispose;
	let each_value = ensure_array_like(/*categories*/ ctx[3]);
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	return {
		c() {
			aside = element("aside");
			div1 = element("div");
			div1.innerHTML = `<div class="logo svelte-a57opy"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg> <span>Secure Vault</span></div>`;
			t2 = space();
			div2 = element("div");
			button0 = element("button");

			button0.innerHTML = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
      New Note`;

			t4 = space();
			nav0 = element("nav");
			h30 = element("h3");
			h30.textContent = "Categories";
			t6 = space();
			ul0 = element("ul");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			t7 = space();
			nav1 = element("nav");
			h31 = element("h3");
			h31.textContent = "Tools";
			t9 = space();
			ul1 = element("ul");
			li = element("li");
			button1 = element("button");
			button1.innerHTML = `<span class="nav-icon svelte-a57opy">🎲</span> <span class="nav-label svelte-a57opy">Password Generator</span>`;
			t13 = space();
			div4 = element("div");
			div3 = element("div");
			button2 = element("button");

			button2.innerHTML = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="17 8 12 3 7 8"></polyline><line x1="12" y1="3" x2="12" y2="15"></line></svg>
        Export`;

			t15 = space();
			button3 = element("button");

			button3.innerHTML = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
        Import`;

			t17 = space();
			button4 = element("button");

			button4.innerHTML = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg>
      Lock Vault`;

			attr(div1, "class", "sidebar-header svelte-a57opy");
			attr(button0, "class", "btn btn-primary w-full");
			attr(h30, "class", "nav-title svelte-a57opy");
			attr(ul0, "class", "nav-list svelte-a57opy");
			attr(nav0, "class", "nav-section svelte-a57opy");
			attr(h31, "class", "nav-title svelte-a57opy");
			attr(button1, "class", "nav-item svelte-a57opy");
			toggle_class(button1, "active", /*currentView*/ ctx[1] === 'generator');
			attr(ul1, "class", "nav-list svelte-a57opy");
			attr(nav1, "class", "nav-section svelte-a57opy");
			attr(div2, "class", "sidebar-content svelte-a57opy");
			attr(button2, "class", "btn btn-ghost btn-sm svelte-a57opy");
			attr(button2, "title", "Export Backup");
			attr(button3, "class", "btn btn-ghost btn-sm svelte-a57opy");
			attr(button3, "title", "Import Backup");
			attr(div3, "class", "footer-actions svelte-a57opy");
			attr(button4, "class", "btn btn-secondary w-full");
			attr(div4, "class", "sidebar-footer svelte-a57opy");
			attr(aside, "class", "sidebar svelte-a57opy");
		},
		m(target, anchor) {
			insert(target, aside, anchor);
			append(aside, div1);
			append(aside, t2);
			append(aside, div2);
			append(div2, button0);
			append(div2, t4);
			append(div2, nav0);
			append(nav0, h30);
			append(nav0, t6);
			append(nav0, ul0);

			for (let i = 0; i < each_blocks.length; i += 1) {
				if (each_blocks[i]) {
					each_blocks[i].m(ul0, null);
				}
			}

			append(div2, t7);
			append(div2, nav1);
			append(nav1, h31);
			append(nav1, t9);
			append(nav1, ul1);
			append(ul1, li);
			append(li, button1);
			append(aside, t13);
			append(aside, div4);
			append(div4, div3);
			append(div3, button2);
			append(div3, t15);
			append(div3, button3);
			append(div4, t17);
			append(div4, button4);

			if (!mounted) {
				dispose = [
					listen(button0, "click", /*click_handler*/ ctx[6]),
					listen(button1, "click", /*click_handler_2*/ ctx[8]),
					listen(button2, "click", /*click_handler_3*/ ctx[9]),
					listen(button3, "click", /*click_handler_4*/ ctx[10]),
					listen(button4, "click", /*click_handler_5*/ ctx[11])
				];

				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (dirty & /*selectedCategory, categories, currentView, selectCategory*/ 27) {
				each_value = ensure_array_like(/*categories*/ ctx[3]);
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul0, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}

				each_blocks.length = each_value.length;
			}

			if (dirty & /*currentView*/ 2) {
				toggle_class(button1, "active", /*currentView*/ ctx[1] === 'generator');
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) {
				detach(aside);
			}

			destroy_each(each_blocks, detaching);
			mounted = false;
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { selectedCategory = 'all' } = $$props;
	let { currentView = 'notes' } = $$props;
	const dispatch = createEventDispatcher();

	const categories = [
		{
			id: 'all',
			label: 'All Notes',
			icon: '📋'
		},
		{
			id: 'personal',
			label: 'Personal',
			icon: '👤'
		},
		{ id: 'work', label: 'Work', icon: '💼' },
		{
			id: 'financial',
			label: 'Financial',
			icon: '💰'
		},
		{
			id: 'medical',
			label: 'Medical',
			icon: '🏥'
		},
		{
			id: 'passwords',
			label: 'Passwords',
			icon: '🔑'
		},
		{ id: 'other', label: 'Other', icon: '📁' }
	];

	function selectCategory(category) {
		dispatch('categoryChange', { category });
		dispatch('viewChange', { view: 'notes' });
	}

	function selectView(view) {
		dispatch('viewChange', { view });
	}

	const click_handler = () => dispatch('newNote');
	const click_handler_1 = category => selectCategory(category.id);
	const click_handler_2 = () => selectView('generator');
	const click_handler_3 = () => dispatch('export');
	const click_handler_4 = () => dispatch('import');
	const click_handler_5 = () => dispatch('lock');

	$$self.$$set = $$props => {
		if ('selectedCategory' in $$props) $$invalidate(0, selectedCategory = $$props.selectedCategory);
		if ('currentView' in $$props) $$invalidate(1, currentView = $$props.currentView);
	};

	return [
		selectedCategory,
		currentView,
		dispatch,
		categories,
		selectCategory,
		selectView,
		click_handler,
		click_handler_1,
		click_handler_2,
		click_handler_3,
		click_handler_4,
		click_handler_5
	];
}

class Sidebar extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { selectedCategory: 0, currentView: 1 }, add_css);
	}
}

export default Sidebar;