// Auto-generated SDK class for runtime:fs
// DO NOT EDIT - Generated by forge-weld

declare const Deno: { core: { ops: any } };
const core = Deno.core;

/**
 * SDK client for runtime:fs extension
 */
export class FsClient {
  readText(): void {
    return core.ops.op_fs_read_text();
  }
  writeText(): void {
    return core.ops.op_fs_write_text();
  }
  readBytes(): void {
    return core.ops.op_fs_read_bytes();
  }
  writeBytes(): void {
    return core.ops.op_fs_write_bytes();
  }
  stat(): void {
    return core.ops.op_fs_stat();
  }
  readDir(): void {
    return core.ops.op_fs_read_dir();
  }
  mkdir(): void {
    return core.ops.op_fs_mkdir();
  }
  remove(): void {
    return core.ops.op_fs_remove();
  }
  rename(): void {
    return core.ops.op_fs_rename();
  }
  copy(): void {
    return core.ops.op_fs_copy();
  }
  exists(): void {
    return core.ops.op_fs_exists();
  }
  watch(): void {
    return core.ops.op_fs_watch();
  }
  watchNext(): void {
    return core.ops.op_fs_watch_next();
  }
  watchClose(): void {
    return core.ops.op_fs_watch_close();
  }
  symlink(): void {
    return core.ops.op_fs_symlink();
  }
  readLink(): void {
    return core.ops.op_fs_read_link();
  }
  appendText(): void {
    return core.ops.op_fs_append_text();
  }
  appendBytes(): void {
    return core.ops.op_fs_append_bytes();
  }
  metadata(): void {
    return core.ops.op_fs_metadata();
  }
  realPath(): void {
    return core.ops.op_fs_real_path();
  }
  tempFile(): void {
    return core.ops.op_fs_temp_file();
  }
  tempDir(): void {
    return core.ops.op_fs_temp_dir();
  }
}

/** Default instance for convenience */
export const fs = new FsClient();
