use crate::ir::{OpSymbol, WeldEnum, WeldModule, WeldStruct};

/// Generator for class-based TypeScript SDK
///
/// Creates object-oriented SDK wrappers for Forge extensions. Each module
/// gets a single client class with methods that wrap core.ops calls.
///
/// # Example Output
///
/// ```typescript
/// export class FsClient {
///   async readTextFile(path: string): Promise<string> {
///     return await core.ops.op_fs_read_text(path);
///   }
/// }
///
/// export const fs = new FsClient();
/// ```
pub struct SdkClassGenerator<'a> {
    module: &'a WeldModule,
}

impl<'a> SdkClassGenerator<'a> {
    /// Create a new SDK class generator
    pub fn new(module: &'a WeldModule) -> Self {
        Self { module }
    }

    /// Generate complete class SDK file
    pub fn generate(&self) -> String {
        let mut output = String::new();

        // File header
        output.push_str(&format!(
            "// Auto-generated SDK class for {}\n",
            self.module.specifier
        ));
        output.push_str("// DO NOT EDIT - Generated by forge-weld\n");
        if let Some(ref doc) = self.module.doc {
            output.push_str("//\n");
            for line in doc.lines() {
                output.push_str(&format!("// {}\n", line));
            }
        }
        output.push('\n');

        // Deno.core declaration
        output.push_str("declare const Deno: { core: { ops: any } };\n");
        output.push_str("const core = Deno.core;\n\n");

        // Generate TypeScript interfaces for structs (needed by methods)
        for s in &self.module.structs {
            output.push_str(&self.generate_struct_interface(s));
            output.push('\n');
        }

        // Generate TypeScript enums
        for e in &self.module.enums {
            output.push_str(&self.generate_enum(e));
            output.push('\n');
        }

        // Generate class
        let class_name = self.class_name();
        output.push_str(&self.generate_class_doc());
        output.push_str(&format!("export class {} {{\n", class_name));

        for op in &self.module.ops {
            output.push_str(&self.generate_method(op));
            output.push('\n');
        }

        output.push_str("}\n\n");

        // Singleton export
        output.push_str(&self.generate_singleton_export(&class_name));

        output
    }

    /// Generate the class name from module specifier
    ///
    /// Examples:
    /// - "runtime:fs" -> "FsClient"
    /// - "runtime:window" -> "WindowClient"
    /// - "runtime:ipc" -> "IpcClient"
    pub fn class_name(&self) -> String {
        // Extract the module name after the colon
        let name = self
            .module
            .specifier
            .split(':')
            .last()
            .unwrap_or(&self.module.name);

        // Convert to PascalCase and append "Client"
        let pascal_case = name
            .chars()
            .next()
            .map(|c| c.to_uppercase().to_string())
            .unwrap_or_default()
            + &name[1..];

        format!("{}Client", pascal_case)
    }

    /// Generate class-level documentation comment
    fn generate_class_doc(&self) -> String {
        let mut output = String::new();
        output.push_str("/**\n");

        if let Some(ref doc) = self.module.doc {
            for line in doc.lines() {
                output.push_str(&format!(" * {}\n", line));
            }
        } else {
            output.push_str(&format!(
                " * SDK client for {} extension\n",
                self.module.specifier
            ));
        }

        output.push_str(" */\n");
        output
    }

    /// Generate a method for an op
    fn generate_method(&self, op: &OpSymbol) -> String {
        let mut output = String::new();

        // Doc comment
        if let Some(ref doc) = op.doc {
            output.push_str("  /**\n");
            for line in doc.lines() {
                output.push_str(&format!("   * {}\n", line));
            }
            output.push_str("   */\n");
        }

        // Method signature
        let visible_params: Vec<_> = op.visible_params().collect();
        let params: Vec<String> = visible_params
            .iter()
            .map(|p| p.to_typescript_param())
            .collect();

        let return_type = op.ts_return_type();
        let async_keyword = if op.is_async { "async " } else { "" };

        output.push_str(&format!(
            "  {}{}({}): {} {{\n",
            async_keyword,
            op.ts_name,
            params.join(", "),
            return_type
        ));

        // Method body - call core.ops with proper await
        let param_names: Vec<String> = visible_params
            .iter()
            .map(|p| p.ts_name.clone())
            .collect();

        let await_keyword = if op.is_async { "await " } else { "" };

        output.push_str(&format!(
            "    return {}core.ops.{}({});\n",
            await_keyword,
            op.rust_name,
            param_names.join(", ")
        ));

        output.push_str("  }");
        output
    }

    /// Generate TypeScript interface for a struct
    fn generate_struct_interface(&self, s: &WeldStruct) -> String {
        let mut output = String::new();

        // Doc comment
        if let Some(ref doc) = s.doc {
            output.push_str("/**\n");
            for line in doc.lines() {
                output.push_str(&format!(" * {}\n", line));
            }
            output.push_str(" */\n");
        }

        output.push_str(&format!("export interface {} {{\n", s.ts_name));

        for field in &s.fields {
            // Field doc comment
            if let Some(ref doc) = field.doc {
                output.push_str("  /**\n");
                for line in doc.lines() {
                    output.push_str(&format!("   * {}\n", line));
                }
                output.push_str("   */\n");
            }

            let readonly = if field.readonly { "readonly " } else { "" };
            let optional = if field.optional { "?" } else { "" };

            output.push_str(&format!(
                "  {}{}{}: {};\n",
                readonly,
                field.ts_name,
                optional,
                field.ty.to_typescript()
            ));
        }

        output.push_str("}");
        output
    }

    /// Generate TypeScript enum
    fn generate_enum(&self, e: &WeldEnum) -> String {
        let mut output = String::new();

        // Doc comment
        if let Some(ref doc) = e.doc {
            output.push_str("/**\n");
            for line in doc.lines() {
                output.push_str(&format!(" * {}\n", line));
            }
            output.push_str(" */\n");
        }

        output.push_str(&format!("export enum {} {{\n", e.ts_name));

        for variant in &e.variants {
            // Variant doc comment
            if let Some(ref doc) = variant.doc {
                output.push_str("  /**\n");
                for line in doc.lines() {
                    output.push_str(&format!("   * {}\n", line));
                }
                output.push_str("   */\n");
            }

            output.push_str(&format!("  {} = \"{}\",\n", variant.name, variant.name));
        }

        output.push_str("}");
        output
    }

    /// Generate singleton export
    ///
    /// Creates a lowercase instance export for convenience:
    /// ```typescript
    /// export const fs = new FsClient();
    /// ```
    fn generate_singleton_export(&self, class_name: &str) -> String {
        // Get the base name without "Client" suffix
        let instance_name = class_name
            .trim_end_matches("Client")
            .chars()
            .next()
            .map(|c| c.to_lowercase().to_string() + &class_name[1..class_name.len() - 6])
            .unwrap_or_else(|| "client".to_string());

        format!("/** Default instance for convenience */\nexport const {} = new {}();\n", instance_name, class_name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{OpParam, WeldType, WeldPrimitive, StructField};

    #[test]
    fn test_class_name_generation() {
        let module = WeldModule::new("runtime_fs", "runtime:fs");
        let gen = SdkClassGenerator::new(&module);
        assert_eq!(gen.class_name(), "FsClient");

        let module = WeldModule::new("runtime_window", "runtime:window");
        let gen = SdkClassGenerator::new(&module);
        assert_eq!(gen.class_name(), "WindowClient");

        let module = WeldModule::new("runtime_ipc", "runtime:ipc");
        let gen = SdkClassGenerator::new(&module);
        assert_eq!(gen.class_name(), "IpcClient");
    }

    #[test]
    fn test_singleton_export_generation() {
        let module = WeldModule::new("runtime_fs", "runtime:fs");
        let gen = SdkClassGenerator::new(&module);
        let class_name = gen.class_name();
        let export = gen.generate_singleton_export(&class_name);

        assert!(export.contains("export const fs = new FsClient()"));
    }

    #[test]
    fn test_method_generation_sync() {
        let module = WeldModule::new("runtime_test", "runtime:test");
        let gen = SdkClassGenerator::new(&module);

        let op = OpSymbol::from_rust_name("op_test_add")
            .param(OpParam::new("a", WeldType::primitive(WeldPrimitive::F64)))
            .param(OpParam::new("b", WeldType::primitive(WeldPrimitive::F64)))
            .returns(WeldType::primitive(WeldPrimitive::F64));

        let method = gen.generate_method(&op);

        assert!(method.contains("add(a: number, b: number): number"));
        assert!(method.contains("return core.ops.op_test_add(a, b)"));
        assert!(!method.contains("async"));
        assert!(!method.contains("await"));
    }

    #[test]
    fn test_method_generation_async() {
        let module = WeldModule::new("runtime_fs", "runtime:fs");
        let gen = SdkClassGenerator::new(&module);

        let op = OpSymbol::from_rust_name("op_fs_read_text")
            .async_op()
            .param(OpParam::new("path", WeldType::string()))
            .returns(WeldType::string());

        let method = gen.generate_method(&op);

        assert!(method.contains("async readText(path: string): Promise<string>"));
        assert!(method.contains("return await core.ops.op_fs_read_text(path)"));
    }

    #[test]
    fn test_struct_interface_generation() {
        let module = WeldModule::new("runtime_test", "runtime:test");
        let gen = SdkClassGenerator::new(&module);

        let mut test_struct = WeldStruct::new("TestData");
        test_struct.fields.push(
            StructField::new("name", WeldType::string())
                .with_doc("The name field"),
        );
        test_struct.fields.push(
            StructField::new("count", WeldType::primitive(WeldPrimitive::F64))
                .optional(),
        );

        let interface = gen.generate_struct_interface(&test_struct);

        assert!(interface.contains("export interface TestData"));
        assert!(interface.contains("name: string"));
        assert!(interface.contains("count?: number"));
        assert!(interface.contains("The name field"));
    }

    #[test]
    fn test_full_generation() {
        let mut module = WeldModule::new("runtime_test", "runtime:test")
            .with_doc("Test extension module");

        module.ops.push(
            OpSymbol::from_rust_name("op_test_hello")
                .async_op()
                .param(OpParam::new("name", WeldType::string()))
                .returns(WeldType::string())
                .with_doc("Say hello to someone"),
        );

        let gen = SdkClassGenerator::new(&module);
        let output = gen.generate();

        // Check header
        assert!(output.contains("Auto-generated SDK class for runtime:test"));
        assert!(output.contains("Test extension module"));

        // Check class
        assert!(output.contains("export class TestClient"));

        // Check method
        assert!(output.contains("async hello(name: string): Promise<string>"));
        assert!(output.contains("Say hello to someone"));

        // Check singleton
        assert!(output.contains("export const test = new TestClient()"));
    }
}
